---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
- name: Update repo cache and install a few prerequisite packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: true
  notify:
    - enable docker service

- name: log into Dockerhub
  docker_login:
    username: "{{ dockerhub_username }}" # tiek padots izpildot playbook
    password: "{{ dockerhub_password }}" # tiek padots izpildot playbook
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
- name: deploy petclinic docker container
  docker_container:
    name: petclinic
    image: "{{ petclinic_docker_image }}"
    ports:
      - "80:8080"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"