---
- name: Update repo cache and install a few prerequisite packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: true

- name: Add the GPG key for the official Docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add the Docker repository to APT sources
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: '644'

- name: Update the package database with the Docker packages
  apt:
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
  notify:
    - enable docker service

- name: log into Dockerhub
  docker_login:
    username: "{{ dockerhub_username }}" # tiek padots izpildot playbook
    password: "{{ dockerhub_password }}" # tiek padots izpildot playbook
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
- name: deploy petclinic docker container
  docker_container:
    name: petclinic
    image: "{{ petclinic_docker_image }}"
    ports:
      - "80:8080"
  vars:
    ansible_python_interpreter: "/usr/bin/python3"